version: '3'
services:
  web:
    image: nginx
    volumes:
      - "./web/default.conf:/etc/nginx/conf.d/default.conf"
      - "../:/var/www/html"
    expose:
      - 80

  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - "../:/var/www/html"
      - "~/.cache/_docker-user:/home/user"
    environment:
      DEBUG: 0
      DATABASE_URL: "mysql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}"

  db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  pma:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
